services:
  frontend:
    image: compilers-project/frontend
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: compilers-project/backend
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

